### ISSUE TITLE
error: too few arguments

### ISSUE THREAD

**Issue by evertonfd** [cs50/submit50#108]
Hello guys, I`m starting the course, but at the first pset I already found some trouble, here follows the code, and at the end, when I use submit50, there`s an error message..

#include <cs50.h>
#include <stdio.h>

int main (void)
{
    //Create the variable
    int n;
    do
    {
        //Prompt the user for input
        printf("How long, in minutes, last your shower? ");
        n = get_int();
    }
    //Loop if negative value
    while(n<=0);
    //Multiplicate the minutes for bottles of water
    int i = n *12;
    //Answer the user the water consuption
    printf("Minutes: %i\n", n);
    printf("Bottles: %i\n", i);
}

It doesn`t submit, says:
usage: submit50 [-h] [-v] problem
submit50: error: too few arguments

**Comment by brianyu28** [comment]
Hey @evertonfd! Welcome to CS50! Per the problem set's instruction's [here](http://docs.cs50.net/2017/x/psets/1/pset1.html#step-3-of-4), be sure you're running `submit50` as

```
submit50 2017/x/water
```

and not just

```
submit50
```

That should allow you to submit the problem!

All the best,
Brian

**Comment by evertonfd** [comment]
Thank you very much!

It worked! :D
________________________________
