### ISSUE TITLE
SSH Authentication hangs if ssh key needs to be unlocked

### ISSUE THREAD

**Issue by crossroads1112** [cs50/submit50#118]
<img src=http://i.imgur.com/SLKslDN.jpg/>

**Comment by crossroads1112** [comment]
Moreover, I'm not even really sure why it is asking me for my passphrase since running that git command directly does not create that prompt. Possibly a missing env variable?

**Comment by dmalan** [comment]
@crossroads1112, once you've inputted your passphrase once on your Arch machine, are any `SSH_`-prefixed environment variables set? E.g., `SSH_ENV` or `SSH_AGENT_PID` or such? Able to identify what our `git` subprocess isn't seeing that your own shell is? Perhaps on point, https://wiki.archlinux.org/index.php/SSH_keys#SSH_agents.
