### ISSUE TITLE
GitHub Releases not split up if there are extra .c files

### ISSUE THREAD

**Issue by nhawke** [cs50/submit50#12]
See the following submit50 repos for examples of this happening for pset2:

It seems that if there is some extra `.c` file that the problems are not properly divided, and instead all the files are all put into every release.

**Comment by dmalan** [comment]
This was actually deliberate for pset2, to allow other *.c and *.h files, lest students have misnamed files or not put things in isolated directories. Over time, we'll start to blacklist more files!
