### ISSUE TITLE
hide credential-related comments from verbose mode?

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#125]
Not enlightening for a student who wants to understand how we're adding, committing, and pushing.

**Comment by brianyu28** [comment]
There would still probably need to be a way to show all the output, though, for our own debugging?

Though, since we take care of tagging server-side now, we could really just publish somewhere the fairly short list of commands for students to submit via git? Which would just be

```bash
git clone https://github.com/submit50/USERNAME.git
cd USERNAME
git checkout -b PROBLEM_NAME

# once files are included...
git add *
git commit -m "message"
git push -u origin PROBLEM_NAME
```

**Comment by dmalan** [comment]
Ja, that makes better sense. Closing!
