### ISSUE TITLE
submit50 and check50 aren`t working

### ISSUE THREAD

**Issue by hantypen** [cs50/submit50#137]
Hi,

I don`t know whether it`s a bug or I`m just doing smth wrong with updates, but I can`t submit and check my code after update50. Here the text of mistake:

> Traceback (most recent call last):
>   File "/opt/pyenv/versions/3.6.0/bin/submit50", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1479, in <module>
>     register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by kzidane** [comment]
Hi @hantypen, which version do you see on the top-right corner? Mind running:

```
$ ~/.cs50/bin/update50
```

and when it's done, click **CS50 IDE > Restart**, and try `submti50` again?

Thank you!

**Comment by hantypen** [comment]
@kzidane, Thanks!
Before restart version was n/a and now v110. Everything is working perfectly right now.

**Comment by kzidane** [comment]
Glad it works! Let us know if you need further assistance! Closing.
