### ISSUE TITLE
Page not found https://github.com/submit50/USERNAME - PSET 0

### ISSUE THREAD

**Issue by blup-Blupon** [cs50/submit50#138]
Hi !

I'm following the instructions to submit pset 0 and step 5 gives me "Page not found (...)":

> 5. Go to https://github.com/submit50/USERNAME, substituting USERNAME for your GitHub username.

Curiously couldn't find a solution using google, I can't be the only one facing this, or did I miss something basic ? I'm opening this link while being logged in on Github.

Thanks 👍

**Comment by brianyu28** [comment]
Hey @blup-Blupon, you'll want to go to this link (with your actual GitHub username in place of `USERNAME`). Does this work for you?

https://github.com/submit50/blup-Blupon

**Comment by blup-Blupon** [comment]
right ! sorry.... I guess my coffee wasn't effective this morning. Thanks for the quick and nice reaction :)

**Comment by brianyu28** [comment]
No problem! Welcome to CS50!
