### ISSUE TITLE
blacklist .~c9_invoke_*

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#156]

**Comment by crossroads1112** [comment]
What does this mean exactly? Do you want it added to the exclude files?

**Comment by dmalan** [comment]
@kzidane know what this is? Guessing it appeared and is C9-specific, in which case we know we can blacklist globally if we want.

**Comment by kzidane** [comment]
If I remember correctly these files are generated automatically by a Cloud9 plugin during collaboration and since they're not excluded they're sometimes submitted with student's code. They used to break `style50` but we're excluding them on ECS now.

**Comment by dmalan** [comment]
Have we seen them enough such that we should block this pattern as well as
.c9 for good measure, even though it's a special-casing?

**Comment by kzidane** [comment]
I've seen it a few times. We should block if not too much trouble. Adds unnecessary clutter to students' submissions.

**Comment by crossroads1112** [comment]
Fixed in push50
