### ISSUE TITLE
filenames with non-UTF-8 characters trigger a UnicodeDecodeError

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#158]
Filenames with non-UTF-8 characters trigger a UnicodeDecodeError:

```
~/workspace/pset4/recover/ $ submit50 cs50/2018/x/recover --verbose
Connecting...
Authenticating...
git config --global credential.https://github.com/submit50.username
git credential-cache --socket /home/ubuntu/.git-credential-cache/submit50 exit
git -c credential.helper='cache --socket /home/ubuntu/.git-credential-cache/submit50 --timeout 604800' -c 
credentialcache.ignoresighup=true credential approve
Preparing...
git clone --bare https://username@github.com/submit50/username /tmp/tmp2o8vlje5
Cloning into bare repository '/tmp/tmp2o8vlje5'...
Password for 'https://username@github.com': 
remote: Counting objects: 220, done.        
remote: Compressing objects: 100% (2/2), done.        
remote: Total 220 (delta 0), reused 3 (delta 0), pack-reused 217        
Receiving objects: 100% (220/220), 5.24 MiB | 5.09 MiB/s, done.
Resolving deltas: 100% (87/87), done.
git checkout --force cs50/2018/x/recover .gitattributes
error: pathspec '.gitattributes' did not match any file(s) known to git.
git config user.email username@users.noreply.github.com
git config user.name username
git symbolic-ref HEAD refs/heads/cs50/2018/x/recover
git config core.excludesFile /tmp/tmpyxoz26th
git add --all
git ls-files
recover.c
git ls-files --exclude-from=/tmp/tmp2o8vlje5/info/exclude --other
"AWA\211\377AVI\211\366AUI\211\325ATL\215%\200\361 "
card.raw
recover
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/submit50", line 11, in <module>
    load_entry_point('submit50==2.4.7', 'console_scripts', 'submit50')()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 128, in main
    submit("submit50", args["slug"])
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 581, in submit
    others = [unescape(other) for other in others]
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 581, in <listcomp>
    others = [unescape(other) for other in others]
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 577, in unescape
    .decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 3: invalid start byte
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
git credential-cache --socket /home/ubuntu/.git-credential-cache/submit50 exit
Submission cancelled.
```

Reproduce with `python3` at the command line with:

```
>>> s = "AWA\211\377AVI\211\366AUI\211\325ATL\215%\200\361 "
>>> s.encode('latin1').decode('unicode-escape').encode('latin1').decode('utf8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 3: invalid start byte
```

Results from https://github.com/cs50/submit50/blob/develop/submit50.py#L564-L581, which is inspired by https://stackoverflow.com/a/46650050/5156190. Goal of those lines is to display the filenames, when summarizing files to be submitted and not submitted, just as the students see them in their directory (as via `ls`), so that they recognize them:

<img width="739" alt="screen shot 2018-03-17 at 3 54 17 pm" src="https://user-images.githubusercontent.com/788678/37559391-8d7ebbd8-29fb-11e8-8995-f4b03c34acaa.png">

I.e., as:

<img width="677" alt="screen shot 2018-03-17 at 3 47 57 pm" src="https://user-images.githubusercontent.com/788678/37559364-ece9ecf6-29fa-11e8-8966-68528b457424.png">

Instead of as:

<img width="569" alt="screen shot 2018-03-17 at 3 55 17 pm" src="https://user-images.githubusercontent.com/788678/37559394-9c9a8a34-29fb-11e8-8048-717805bc27e1.png">

We could pass `-z` to `git-ls-files`, to avoid `git`'s escaping of Unicode characters. But then [`spawnu`](http://pexpect.readthedocs.io/en/stable/api/pexpect.html#handling-unicode) tends to choke, since it needs to know the encoding of the characters it's seeing (and doesn't like unrecognized encodings, as might happen with accidentally created filenames).

Perhaps worth noting is how `zip` and `tar` handle this anomalous filename:

```
~/workspace/pset4/ $ zip -r recover.zip recover/
  adding: recover/ (stored 0%)
  adding: recover/recover.c (deflated 61%)
  adding: recover/recover (deflated 62%)
  adding: recover/AWAAVIAUITL% (stored 0%)
~/workspace/pset4/ $ tar cvf recover.tar recover
recover/
recover/recover.c
recover/recover
recover/AWA\211\377AVI\211\366AUI\211\325ATL\215%\200\361
```

**Comment by glennholloway** [comment]
@dmalan @crossroads1112 ... Does anyone know why SOO many students end up with files having such names when they're working on `recover`? It is just failure to initialize their output filename buffers?

**Comment by kzidane** [comment]
@glennholloway might be the case that the don't allocate enough memory for the filename?

**Comment by kzidane** [comment]
@glennholloway I just noticed you mentioned that in your second question. I think that's probably the case.

**Comment by crossroads1112** [comment]
Why not replace any of the invalid characters with [Unicode's replacement character](https://codepoints.net/U+FFFD) (as C9 IDE currently does)? `.decode` supports this directly e.g. we could do

```python

s = "AWA\211\377AVI\211\366AUI\211\325ATL\215%\200\361 "
s.encode('latin1').decode('unicode-escape').encode('latin1').decode('utf8', 'replace')
```
which results in

```
AWA��AVI��AUI��ATL�%�� 
```

If we wanted to make it match `ls` directly, we could add on an additional `.replace('\uFFFD', '?')` on to the end.

**Comment by dmalan** [comment]
How does this strike you, @crossroads1112?

https://github.com/cs50/submit50/pull/159

One minor aesthetic bug is this one in verbose mode:

<img width="725" alt="screen shot 2018-03-17 at 9 47 40 pm" src="https://user-images.githubusercontent.com/788678/37561771-8c115a62-2a2d-11e8-9326-f9380176832a.png">

Specifically, when this line, https://github.com/cs50/submit50/blob/unicode/submit50.py#L574, for instance, doesn't output any files, we nonetheless now send a `\n` to `sys.stdout.buffer`. Else the next command ends up on the same line as `git-ls-files`'s output, when`git-ls-files` does have output. Thoughts on how best to output that `\n` conditionally? Can we somehow keep track of whether any bytes were actually logged to `sys.stdout.buffer`, per https://github.com/cs50/submit50/blob/unicode/submit50.py#L352-L356, during an invocation of `run`?

**Comment by crossroads1112** [comment]
I think the correct fix to this is just to make sure that if the command had any output, that it ends in a newline (else we print one): 

```python
command_output = child.read()
# If we're in verbose mode and the command didn't end with a newline, output one.
if run.verbose and not quiet and command_output and command_output[-1] not in [ord("\n"), "\n"]:
    sys.stdout.write("\n")
# ...
return command_output.strip()
```

**Comment by crossroads1112** [comment]
push50 now excludes these files (just as we do .git and .c9 files).
