### ISSUE TITLE
rename "slug" to "branch"

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#167]
Might as well adopt a word students and teachers will see elsewhere?

**Comment by Jelleas** [comment]
Ultimately we use the slug as a branch on the submit50/check50 orgs. However a slug itself is composed of <org>/<repo>/<branch>/<problem>. As such it's quite confusing to expose this as a branch. Even more so if a teacher decides to start writing checks.

The old name for slug was identifier, but as we exclusively used the term slug internally, I figured it's more appropriate to call it that in the tool as well.

**Comment by dmalan** [comment]
Oh, true, it's not just a branch... Okay might as well leave be.

**Comment by crossroads1112** [comment]
Closing per email thread.
