### ISSUE TITLE
add -u/--user flag that specifies username to use for SSH submissions

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#169]
Use case is so that lab50 can have `bot50` submit on a student's behalf. Could just use raw `git` commands for such, but then `!exclude` and such wouldn't be respected. Might also be helpful for more-comfy users who have SSH keys associated with multiple GitHub accounts?

**Comment by crossroads1112** [comment]
Probably best to make this a git config option as it was before (though optional now) since it'd be annoying to have to specify this all the time.

**Comment by crossroads1112** [comment]
> Well, the default could still be to use the SSH trick, in the absence of -u, no?

Yeah, that's what I was thinking.

If we make it a git config option, `submit50` never has to know about it, lib50 can just take care of it (and we get the feature in check50 for free). It's also less annoying to the students you mentioned who have multiple GitHub accounts.

**Comment by dmalan** [comment]
Okay, let's do the `git config` approach.

**Comment by crossroads1112** [comment]
this is fixed now that we are moving to ids. `git config --global cs50.github.id <student id>`.
