### ISSUE TITLE
How to unable check50 and submit50?

### ISSUE THREAD

**Issue by 0v0smiling** [cs50/submit50#171]
This may be a ridiculously simple question, I apologize beforehand.

I started cs50 on edX two days ago but just couldn't figure out how to run check50 and submit50. 
1) tried cs50.me. 
Result: page jumped to authentication page, but the button for authentication is light green/grey and cannot be clicked.
2) tried SSH
Result: all set, added SSH to github and ran code on cloud terminal, but when trying to run submit50 for pset1, it still said account not authenticated.
3) tried to switch from a private workspace to a public one.
Result: fails, account not authenticated when trying to submit hello.c

What exactly is the way to authenticate submit50 and check50? 
Thank you!

**Comment by crossroads1112** [comment]
> Result: page jumped to authentication page, but the button for authentication is light green/grey and cannot be clicked.

Ensure you are using a modern browser and have adblockers disabled and javascript enabled. In the future, please direct questions like these to cs50's numerous online forums (Facebook, Reddit, StackExchange, etc.)
