### ISSUE TITLE
Error Certified while install submit50

### ISSUE THREAD

**Issue by winzaldi** [cs50/submit50#174]
help, cant install submit50, below the process instalation.

mbpro:Documents aldi$ pip3 install submit50
Collecting submit50
  Using cached https://files.pythonhosted.org/packages/e2/94/c14f40e36c7ddb6e88955df11dba43c2f3f4ba45af8618f64de5273fef19/submit50-2.4.8.tar.gz
Requirement already satisfied: backports.shutil_get_terminal_size in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: backports.shutil_which in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: pexpect>=4.0 in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: termcolor in /usr/local/lib/python3.7/site-packages (from submit50)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/site-packages (from pexpect>=4.0->submit50)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->submit50)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->submit50)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->submit50)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->submit50)
Building wheels for collected packages: submit50
  Running setup.py bdist_wheel for submit50 ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/tmpvbceqcropip-wheel- --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying submit50.py -> build/lib
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py", line 82, in <module>
      version="2.4.8"
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 224, in run
      self.run_command('install')
    File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py", line 38, in run
      raise RuntimeError("Error installing certificates.")
  RuntimeError: Error installing certificates.
  
  ----------------------------------------
  Failed building wheel for submit50
  Running setup.py clean for submit50
Failed to build submit50
Installing collected packages: submit50
  Running setup.py install for submit50 ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-hjo509oe-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py", line 82, in <module>
        version="2.4.8"
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py", line 38, in run
        **raise RuntimeError("Error installing certificates.")
    RuntimeError: Error installing certificates.**
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-hjo509oe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x6/1b5mtvvs0wv4jl75nsnsp2xh0000gp/T/pip-build-789khql2/submit50/

thanks before,

**Comment by dmalan** [comment]
Hi @winzaldi , does `sudo pip3 install submit50` fix?

**Comment by winzaldi** [comment]
> Hi @winzaldi , does `sudo pip3 install submit50` fix?

Hi @dmalan  still error with same message...
 i've tried with sudo pip3 install submit50 and sudo -H pip3 install submit50 and still error like before.

mbpro:Caches aldi$ sudo pip3 install submit50
The directory '/Users/aldi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/aldi/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting submit50
  Downloading https://files.pythonhosted.org/packages/e2/94/c14f40e36c7ddb6e88955df11dba43c2f3f4ba45af8618f64de5273fef19/submit50-2.4.8.tar.gz
Requirement already satisfied: backports.shutil_get_terminal_size in /usr/local/lib/python3.7/site-packages (from submit50) (1.0.0)
Requirement already satisfied: backports.shutil_which in /usr/local/lib/python3.7/site-packages (from submit50) (3.5.2)
Requirement already satisfied: pexpect>=4.0 in /usr/local/lib/python3.7/site-packages (from submit50) (4.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from submit50) (2.20.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from submit50) (1.11.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.7/site-packages (from submit50) (1.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/site-packages (from pexpect>=4.0->submit50) (0.6.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->submit50) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->submit50) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->submit50) (2018.10.15)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->submit50) (1.24.1)
Installing collected packages: submit50
  Running setup.py install for submit50 ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-ds4nkiz5/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-2hl9vmx1/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-ds4nkiz5/submit50/setup.py", line 82, in <module>
        version="2.4.8"
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-ds4nkiz5/submit50/setup.py", line 38, in run
        raise RuntimeError("Error installing certificates.")
    RuntimeError: Error installing certificates.
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-ds4nkiz5/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-2hl9vmx1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-ds4nkiz5/submit50/

**Comment by Jelleas** [comment]
Problem here is that `setup.py` still checks for `"/Applications/Python 3.6/Install Certificates.command"` that doesn't exist when Python is installed via homebrew.

@coltonoscopy created a pull request a while ago (before we started developing 3.0) @ https://github.com/cs50/submit50/pull/162 that should fix this problem specifically for homebrew. I updated the pr and that should hopefully fix this problem when merged.

Till then, you can try: `pip install git+https://github.com/cs50/submit50@sslfix`.

**Comment by winzaldi** [comment]
@Jelleas , i've success install submit 50 after read your solution on check50 issue... 
i used command 

_pip3 install git+https://github.com/cs50/submit50_ 

and everything work fine

Thanks you @Jelleas  and @dmalan  :)

**Comment by wassay76** [comment]
i am having same problem cant install submit50
 pip3 install git+https://github.com/cs50/submit50
Collecting git+https://github.com/cs50/submit50
  Cloning https://github.com/cs50/submit50 to c:\users\ashraf house\appdata\local\temp\pip-req-build-nosfedn7
  Running command git clone -q https://github.com/cs50/submit50 'C:\Users\ashraf house\AppData\Local\Temp\pip-req-build-nosfedn7'
Collecting lib50<4,>=3 (from submit50==3.0.3)
  ERROR: Could not find a version that satisfies the requirement lib50<4,>=3 (from submit50==3.0.3) (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8)
ERROR: No matching distribution found for lib50<4,>=3 (from submit50==3.0.3)
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by wassay76** [comment]
pls hel

**Comment by tommylenz** [comment]
Hey @wassay76, hey @walidAhmadyar! Could you please provide some information, so that I am able to recreate your error? Could you give me:
* Your Windows version as per [this](https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running) guide
* Your python version (run `python -V` or `python3 -V` in your console)

Have you installed the Linux subsystem already? Submit50 uses lib50, which isn't avaiable under Windows. Go ahead and [install the Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) , restart your PC and try again!

**Comment by wassay76** [comment]
hi thanks for your concern
i am using windows 10 pro
i have python version 3.8.3

**Comment by tommylenz** [comment]
Have you tried installing the Linux Subsystem? Otherwise, you won‘t be able to use lib50‘s functionality that submit50 depends on! (@I
others correct me when I am wrong here!)

If you need help setting it up, don‘t hesitate to ask! 😀

**Comment by walidAhmadyar** [comment]
@tommylenz 
Just afraid of losing my windows and windows data after installing that!
And I try to push using GitHub ,
 so if I can Push my projects using GitHub I will not need to install that submit50

**Comment by tommylenz** [comment]
@walidAhmadyar I can understand that! But if you follow the tutorial correctly, you don't have to worry about your data! You don't override your windows os, you just extend it in a way that you are able to run a linux command prompt next to it. If you feel less secure, how about using the [CS50 IDE?](https://ide.cs50.io) It's suitable for coding every problem set, and all tools (like submit50 for example) you could need are already installed!

**Comment by walidAhmadyar** [comment]
@tommylenz 
thanks, CD50 IDE is good option but i don't have access to internet all the time!,
So, i install the Git on my windows, i can push my project using that, and i can run python using flask as well. 
but i don't  know if i face with any problem on future ?

**Comment by tommylenz** [comment]
For completing CS50, you don't neccessarily need an active internet connection all the time, although you could benefit from one. Just try it out! Obviously, depending on what your final project will be about you will need an active connection then, and you will need one depending on what you will do after completing CS50, but that's beyond our scope here.
Keep on going! :smile:
