### ISSUE TITLE
blacklist sensitive dot directories

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#177]
Even though it might be a bit inelegant, probably best to blacklist dirs like

* `~/.ssh`
* `~/.c9`

from being submitted (unless overridden by, e.g., a `-d` flag) for cases when student is working on a program in their home directory.

**Comment by dmalan** [comment]
CC @kzidane @brianyu28

**Comment by Jelleas** [comment]
This is already implemented in `lib50.files` @ https://github.com/cs50/lib50/blob/c671ddf1fa3b52587457a90f2e55c6a67e37bc2c/lib50/_api.py#L122 This is a blacklist that cannot be overriden and it should not. You would never want to submit `.git` for instance. A command line option is not the right way to go here, as that is in the students control. A student from the perspective of submit50 should not decide which files are submitted.

By default all hidden files/dirs are not submitted, but that can be overriden with `!include "*"`.
