### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#18]
In https://github.com/cs50/submit50/blob/master/Makefile:

* add `python3`
* remove `expect`, `jq`, `util-linux` (I think last is safe to remove now)

Can the Python dependencies in `requirements.txt` be installed as `apt-get` dependencies? E.g., for dependency `foo`, does `python3-foo` exist, so we can avoid calling `pip3` in `after-install.sh`, per http://askubuntu.com/questions/327543/how-can-a-debian-package-install-python-modules-from-pypi?

Either way, `requirements.txt` shouldn't end up in `bin`. Ideally should be integrated into `Makefile` or `after-install.sh`.

**Comment by brianyu28** [comment]
There are four dependencies in `requirements.txt` right now: `getch`, `pexpect`, `pytz`, and `termcolor`.

`python3-pexpect` and `python3-termcolor` exist as `apt-get` packages, but `python3-getch` and `python3-pytz` do not.

**Comment by brianyu28** [comment]
I added dependency installation to b8b695a
