### ISSUE TITLE
Problem with submit50

### ISSUE THREAD

**Issue by NadiaPegado** [cs50/submit50#189]
Hello everyone, I'm having trouble doing submit50, it doesn't work, I'm using windows 10. Can anyone help?

**Comment by aliabusaleh** [comment]
Same problem i can't download it

**Comment by tahachau** [comment]
can't install either

**Comment by ashermkn1** [comment]
Try installing the Windows Subsystem for Linux and then running it from there

**Comment by crossroads1112** [comment]
`submit50` does not currently support Windows outside the Windows Subsystem for Linux (Windows 10 only).
