### ISSUE TITLE
replace submit50/submit50's branches with just one config file on master

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#19]
It's already becoming a bit unmaintainable having one branch per `exclude` file. And easy to make a mistake, as by pushing to wrong remote branch. Am thinking we should just replace all of our branches with an `exclude/` directory on the `master` branch of `submit50/submit50`, inside of which is `foo`, `bar`, `baz`, etc., where each of `foo`, `bar`, and `baz` are former branches' names (i.e., problems).

Or, instead of using `submit50/submit50` in this way, we could bake supported problems (i.e., repo names) into cs50.me, so that the `submit50` CLI instead contacts cs50.me, though that somewhat breaks the abstraction barrier.

**Comment by brianyu28** [comment]
Addressed by https://github.com/cs50/submit50/pull/15/commits/fca464cb24317b3db49785c4994800f8651ef890. This expects the `master` branch to be organized like this: https://github.com/submit50dev/submit50dev

**Comment by brianyu28** [comment]
I've gone ahead and organized the exclude files in my fork of `submit50/submit50`, available here:

https://github.com/brianyu28/submit50-excludes/tree/master

Also included a `VERSION` file per #20.

If you add a `master` branch to `submit50/submit50`, I'll submit a PR.

**Comment by brianyu28** [comment]
Addressed here:

https://github.com/submit50/submit50/tree/master

Might be good to make `master` `submit50/submit50`'s default branch instead of `hello`, though it might not matter so much if we're going to switch to config files in `CS50.me` anyhow
