### ISSUE TITLE
I submit the .c file on cs50 lab website but I cannot see my score 

### ISSUE THREAD

**Issue by timeneverdie** [cs50/submit50#198]
Up to now, I submit two files and they can be found in /me50/ on Github, but only one file can be checked score on cs50.me website, the other is like missing.

Is the server still checking the score? Or I just met the bug?

**Comment by kzidane** [comment]
Afraid GitHub has been experiencing some issues! See https://cs50.statuspage.io/.

**Comment by timeneverdie** [comment]
> Afraid GitHub has been experiencing some issues! See https://cs50.statuspage.io/.

I see my score now, maybe some bugs are there. It's fine now.
