### ISSUE TITLE
submit50 update not working

### ISSUE THREAD

**Issue by bolorundurovj** [cs50/submit50#200]
![image](https://user-images.githubusercontent.com/20609046/70255304-dbdd6e80-1786-11ea-807c-427d92de6a6d.png)
![image](https://user-images.githubusercontent.com/20609046/70255367-f4e61f80-1786-11ea-82a5-d1199f306253.png)
keeps giving this error anytime i try to submit : You have an old version of submit50. Please update your version of submit50, then re-run submit50!

**Comment by dmalan** [comment]
Be sure you have Python 3 installed, then run `pip uninstall submit50` and then `pip3 install submit50`!

**Comment by bolorundurovj** [comment]
I have done just that
