### ISSUE TITLE
Problem downloading submit 50

### ISSUE THREAD

**Issue by LukeJosephPolackal** [cs50/submit50#210]
I'm unable to download project 50 using the instructions prescribed using the command `pip3 install submit50`. How do I fix this?
Here's the error displayed on command prompt:
C:\Users\josep>pip3 install submit50
Collecting submit50
Using cached submit50-3.0.2.tar.gz (5.5 kB)
ERROR: Command errored out with exit status 1:
command: 'c:\users\josep\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\josep\AppData\Local\Temp\pip-install-71e1f474\submit50\setup.py'"'"'; file='"'"'C:\Users\josep\AppData\Local\Temp\pip-install-71e1f474\submit50\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\josep\AppData\Local\Temp\pip-install-71e1f474\submit50\pip-egg-info'
cwd: C:\Users\josep\AppData\Local\Temp\pip-install-71e1f474\submit50
Complete output (5 lines):
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\josep\AppData\Local\Temp\pip-install-71e1f474\submit50\setup.py", line 2, in
raise RuntimeError("submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that.")
RuntimeError: submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that.
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by crossroads1112** [comment]
`submit50` does not currently support Windows outside the Windows Subsystem for Linux. If you are comfortable installing it you can find instructions [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Otherwise, you can use submit50 in the CS50 IDE. 

In the future, best to post questions in one of these forums: http://cs50.edx.org/communities
