### ISSUE TITLE
How do I upload Problem set 0

### ISSUE THREAD

**Issue by divyapalat** [cs50/submit50#213]

**Comment by crossroads1112** [comment]
You can find submission instructions [here](https://cs50.harvard.edu/x/2020/psets/0/scratch/#how-to-submit). If you have any more questions, please do use one of our online forums designed for that purpose (you can find a list of them [here](https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/)).
