### ISSUE TITLE
I don't understand how to submit

### ISSUE THREAD

**Issue by Tiberius-Rex** [cs50/submit50#227]
I spent $150 on this course and the submission process is by far the most confusing part so far.
I have a windows 10, and from what I'm reading I can't use submit50 without a virtual Linux running on my system?
I just want credit for my work, is there really no simpler way to do so?
and if not can someone describe how to submit this code without acting like everyone reading it is a 20 year coder?
This is frustrating.

**Comment by dmalan** [comment]
If taking CS50x, best to use and submit via [CS50 IDE](https://ide.cs50.io/), which has everything you need!
