### ISSUE TITLE
My program gives right answer ,But still there are a red marks at the check50 !

### ISSUE THREAD

**Issue by Farah2030** [cs50/submit50#234]
Hi everyone,

My program gives right answer ,But still there are a red marks at the check50 !
Does anyone know where is the mistake ?

Thank you,
Farah Nassan
------------------------------------------------------------------------------------------------------------------------
#include <cs50.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

// Max number of candidates
#define MAX 9

// Candidates have name and vote count
typedef struct
{
    string name;
    int votes;
}
candidate;

// Array of candidates
candidate candidates[MAX];

// Number of candidates
int candidate_count;
int voter_count;
// Function prototypes
bool vote(string n);
void print_winner(void);

int main(int argc, string argv[])
{
    // Check for invalid usage
    if (argc < 2)
    {
        printf("Usage: plurality [candidate ...]\n");
        return 1;
    }

    // Populate array of candidates
    candidate_count = argc - 1;
    if (candidate_count > MAX)
    {
        printf("Maximum number of candidates is %i\n", MAX);
        return 2;
    }
    for (int i = 0; i < candidate_count; i++)
    {
        candidates[i].name = argv[i + 1];
        candidates[i].votes = 0;
    }

    voter_count = get_int("Number of voters: ");
    string name;

    // Loop over all voters
    for (int i = 0; i < voter_count; i++)
    {
        name = get_string("Vote: ");

        // Check for invalid vote
        if (!vote(name))
        {
            printf("Invalid vote.\n");
        }
    }

    // Display winner of election
    print_winner();

}

// Update vote totals given a new vote
bool vote(string n)
{
    int t = 0;
    for (int j = 0; j < candidate_count; j++)
    {
        if (strcmp(candidates[j].name, n) == 0)
        {
            t++;
            candidates[j].votes += 1;
        }
    }
    if (t == 1)
    {
        return true;
    }
    return false;
}

// Print the winner (or winners) of the election

void print_winner(void)
{
    int max = 0;
    for (int j = 0; j < candidate_count; j++)
    {
        if (candidates[j].votes > max)
        {
            max = candidates[j].votes;
        }
    }

    for (int j = 0; j < candidate_count; j++)
    {
        if (candidates[j].votes == max)
        {
            printf("%s\n", candidates[j].name);
        }
    }
    return;
}

-------------------------------------------------------------------------------------------------------------------------------

Results for cs50/problems/2020/x/plurality generated by check50 v3.1.2
:) plurality.c exists
:) plurality compiles
:) vote returns true when given name of first candidate
:) vote returns true when given name of middle candidate
:) vote returns true when given name of last candidate
:) vote returns false when given name of invalid candidate
:) vote produces correct counts when all votes are zero
:) vote produces correct counts after some have already voted
:) vote leaves vote counts unchanged when voting for invalid candidate
:( print_winner identifies Alice as winner of election
    print_winner function did not print winner of election
:( print_winner identifies Bob as winner of election
    print_winner function did not print winner of election
:( print_winner identifies Charlie as winner of election
    print_winner function did not print winner of election
:( print_winner prints multiple winners in case of tie
    print_winner function did not print both winners of election
:( print_winner prints all names when all candidates are tied
    print_winner function did not print all three winners of election

**Comment by tommylenz** [comment]
Hm, I have to admit that I can't replicate your issue. I copied your code, intended everything correctly and all check50 checks passed.
Try to use `style50 plurality.c` to check your program's style! Does it work then?

**Comment by Farah2030** [comment]
it solved
