### ISSUE TITLE
Sumbit50 not installing

### ISSUE THREAD

**Issue by mibnrashid** [cs50/submit50#236]
Hi everyone, I have tried installing submit50 but it isn't working every time I try it comes like this:
![image](https://user-images.githubusercontent.com/50634513/90336065-03f1c280-dfe2-11ea-96da-f5f81a2c5bb0.png)

**Comment by mibnrashid** [comment]
> Hi everyone, I have tried installing submit50 but it isn't working every time I try it comes like this:
> ![image](https://user-images.githubusercontent.com/50634513/90336065-03f1c280-dfe2-11ea-96da-f5f81a2c5bb0.png)

Just for information I am on a windows system

**Comment by VictorGhioca** [comment]
I have also this problem, tried about everything i could but with no result.

**Comment by tommylenz** [comment]
As you see inside the error message, submit50 doesn't support Windows directly. You have to install the so called Linux subsystem and use submit50 within that. You can follow [this guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10) if you want to do so.

Do you have a specific reason for trying to use submit50 outside of CS50's IDE?

**Comment by VictorGhioca** [comment]
I was trying to install submit50 as per cs50 documentation in order to upload the Scratch file for problem set 0.

**Comment by tommylenz** [comment]
Oh, I see! But you can do this via CS50’s own IDE as well.
How did you fix the issue then?

**Comment by VictorGhioca** [comment]
I think the documentation is slightly confusing for a newbie. I tried to install Submit50 (as per documentation) and i got the error above and after that i tried to upload the Scratch file directly on Git where i encountered other issues (with authorization and some permissions, idk the interface is confusing for a beginner) but in the end i found the solution in the CS50 "dashboard" and got to this link (https://cs50.harvard.edu/x/2020/psets/0/scratch/) which allowed me to upload the Scratch file. I guess this is how software development works these days :)

**Comment by tommylenz** [comment]
Yes, you are right! Working with Git is a bit strange for beginners, this is why CS50 encourages you to use check50, submit50 and CS50's IDE, all of which are using git and similar _confusing_ tools behind the scenes.

It's always best to follow the "How to submit" guide at the end of the problem set - but don't worry, for the rest of the problem sets the instructions will be quite similar, just the Scratch program is uploaded this way. Have fun on your journey!

**Comment by VictorGhioca** [comment]
Thank you for your time Thomas! As well to you.

**Comment by ranielbabu** [comment]
> As you see inside the error message, submit50 doesn't support Windows directly. You have to install the so called Linux subsystem and use submit50 within that. You can follow [this guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10) if you want to do so.
> 
> Do you have a specific reason for trying to use submit50 outside of CS50's IDE?

I was trying to install submit50 as per cs50 documentation in order to upload the Scratch file for problem set 0.

is there any other way to solve this issue

**Comment by cmlsharp** [comment]
As it says in the instructions, [here](https://cs50.harvard.edu/x/2020/psets/0/scratch/), you can also submit by uploading your `.sb3` file here: https://submit.cs50.io/upload/cs50/problems/2020/x/scratch
