### ISSUE TITLE
can not download submit50 

### ISSUE THREAD

**Issue by ranielbabu** [cs50/submit50#243]
Collecting submit50
  Using cached submit50-3.0.2.tar.gz (5.5 kB)
    _

ERROR: Command errored out with exit status 1:
     command: 'c:\users\chrat\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chrat\\AppData\\Local\\Temp\\pip-install-zkj2ej9c\\submit50\\setup.py'"'"'; __file__='"'"'C:\\Users\\chrat\\AppData\\Local\\Temp\\pip-install-zkj2ej9c\\submit50\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\chrat\AppData\Local\Temp\pip-pip-egg-info-ku_qy1u7'
         cwd: C:\Users\chrat\AppData\Local\Temp\pip-install-zkj2ej9c\submit50\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\chrat\AppData\Local\Temp\pip-install-zkj2ej9c\submit50\setup.py", line 2, in <module>
        raise RuntimeError("submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that.")
    RuntimeError: submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that.

_
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by curiouskiwi** [comment]
The solution is given to you in the error message you received:

> "submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that."

**Comment by ranielbabu** [comment]
> The solution is given to you in the error message you received:
> 
> > "submit50 does not support Windows directly. Instead, you should install the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install submit50 within that."

is there any other way that i can use ?
