### ISSUE TITLE
Hello assignment not showing up in cs50.me

### ISSUE THREAD

**Issue by mouse-glitch** [cs50/submit50#245]
I'm on Chapter 1 in Cs50 AP and I just finished problem set 1, which is to complete Hello, Mario (Less) or Mario (More), and Cash or Credit. I've submitted all of them, and went to check in cs50.me. For some reason Hello shows up as incomplete on cs50.me, the grade is 0%.  I've tried resubmitting the assignment. Does anyone know how to fix this? 

P.S. First post on Github. Sorry if this is posted in the wrong place.

**Comment by kzidane** [comment]
Please email sysadmins@cs50.harvard.edu about this issue.

**Comment by mouse-glitch** [comment]
Ok, thank you =)
