### ISSUE TITLE
Github Plain authentication via git is going EOL 2021-08

### ISSUE THREAD

**Issue by 133794m3r** [cs50/submit50#248]
Submit50 currently uses standard password authentication with the git CLI, which is going EOL in the coming year. I didn't already see an issue for this but since this program is used by all CS50 courses I figured it'd be something you guys should be tracking if you weren't already.

https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

It says August 2021 which is a ways off but still it's best to put it on the board now instead of waiting till later so that as many people as can can utilize it. Since I believe you also use submit50 from within your CS50 IDE so that environment would also have to be updated also with this new change.

**Comment by 133794m3r** [comment]
I'm surprised that this issue is still unacknowledged as of yet. It's less than 1 month and this utility will no longer work.

**Comment by kylevitale** [comment]
Any update on this? Seems like impending doom is coming.

**Comment by dmalan** [comment]
Not to worry, there'll be updated instructions next week!
