### ISSUE TITLE
Fails, then succeeds on same input

### ISSUE THREAD

**Issue by glennholloway** [cs50/submit50#25]
In release 96 of `ide50`, I ran `submit50` twice in rapid succession, changing nothing between the two runs. The first failed, but the second succeeded.

    ~/workspace/pset1/ $ submit50 2017/spring/hello
    GitHub username: glennholloway
    GitHub password: ***********
    Authentication Code: 508866
    Looks like we haven't enabled submit50 for your account yet! Let sysadmins@cs50.harvard.edu know your GitHub username!
    Submission cancelled.
    ~/workspace/pset1/ $ submit50 2017/spring/hello
    GitHub username: glennholloway
    GitHub password: ***********
    Authentication Code: 215120
    Files that will be submitted:
     hello.c
    Keeping in mind the course's policy on academic honesty, are you sure you want to submit these files? yes
    Submitted cs50/2017/spring/hello! See https://github.com/submit50/glennholloway/tree/cs50/2017/spring/hello.
    ~/workspace/pset1/ $

**Comment by dmalan** [comment]
@brianyu28 do we know why this might have happened?

**Comment by brianyu28** [comment]
Hm, the relevant lines of code here (in their current form) would be:

```python
    res = requests.get("https://api.github.com/repos/{}/{}".format(ORG_NAME, username), auth=(username, password))
    if res.status_code != 200:
        raise Error("Looks like submit50 isn't enabled for your account yet. Log into https://cs50.me/ in a browser, click \"Authorize application\", then re-run submit50 here!")
```

So the only reason that error message would appear is if the API call to [get the user's `submit50` repository](https://developer.github.com/v3/repos/#get) returned a non-200 status. Not sure why that would happen given that the repository definitely existed, maybe an internet connectivity issue or a temporary lapse in GitHub's API availability?

**Comment by dmalan** [comment]
Closing for now, presuming GitHub issue.
