### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by fayrisbaloch** [cs50/submit50#259]
Hello, is it necessary for me, as an international online student to get access to submit50?

**Comment by MoRakha9** [comment]
i have no idea how to submit my assignment solution, any guides?

**Comment by dmalan** [comment]
> Hello, is it necessary for me, as an international online student to get access to submit50?

Everything you'll need for CS50x is installed in CS50 IDE, including `submit50`!

**Comment by dmalan** [comment]
> i have no idea how to submit my assignment solution, any guides?

See the **How to Submit** section of each problem!
