### ISSUE TITLE
Submit50 error

### ISSUE THREAD

**Issue by abhya-r** [cs50/submit50#260]
I'm unable to submit my lab files through submit50. It reads as GITHUB Username or password invalid.I entered the correct details.Please help

Make sure your username and/or password are valid and submit50 is enabled for your account. To enable submit50, please go to https://submit.cs50.io in your web browser and try again. If you're
>  using GitHub two-factor authentication, you'll need to create and use a personal access token with the "repo" scope instead of your password. See https://cs50.ly/github-2fa for more 

This is what I got.

**Comment by dmalan** [comment]
Be sure to follow each of those steps! And best to post in https://cs50.harvard.edu/communities with questions!
