### ISSUE TITLE
Cannot use the check50 or submit50 links for my cs50 course - keep getting error message 

### ISSUE THREAD

**Issue by prathamarora16** [cs50/submit50#264]
The error messages look like the following:

![image](https://user-images.githubusercontent.com/84988862/127376837-765eecd6-7ebe-47f4-84dd-6b4be50dd328.png)

![image](https://user-images.githubusercontent.com/84988862/127376854-efd11619-ffc2-45d7-8bad-fb45867bdcf3.png)

if anyone knows how to fix the issue please let me know as soon as possible.

thanks!

**Comment by rongxin-liu** [comment]
Are you still having issues using submit50/check50?

**Comment by prathamarora16** [comment]
No for that week it worked out! Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
