### ISSUE TITLE
New Submit50 SSH key

### ISSUE THREAD

**Issue by dayojohn19** [cs50/submit50#268]
I was prompted that there is a new way of submitting, and need of SSH key,, followed all the instructions then after i uploaded, I got stuck here 
****
Uploading................................................................................................................................................................................................................................................................................
****
and 
*y
y
y
y
y
y
*****
anyone having same issue in the new way of submitting ??

**Comment by rongxin-liu** [comment]
Which problem set are you working on exactly?

**Comment by dayojohn19** [comment]
i just used git push, did not use submit 50 this time , 
    On Sunday, August 29, 2021, 07:00:42 AM GMT+8, Rongxin Liu ***@***.***> wrote:  
 
 


Which problem set are you working on exactly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
