### ISSUE TITLE
Cannot submit from local IDE

### ISSUE THREAD

**Issue by MakingStuffs** [cs50/submit50#270]
Hi guys, 

I have been trying to submit with the submit50 tool but always get the following error:

`You have an outdated version of submit50. Please upgrade.`

I then run `pip3 install --upgrade submit50` which then tells me I do not need to instal anything. It just prints a load messages along the line of: `Requirement already satisfied`

**Comment by vinsonjk** [comment]
did you figure this out?
. I cannot submit either.

**Comment by dmalan** [comment]
What OS are you running `submit50` on? And what's the output of `pip3 show submit50`?

**Comment by MakingStuffs** [comment]
Hi @dmalan,

Thanks for getting back to me, the output of `pip3 show submit50` is as follows: 

```
Name: submit50
Version: 3.1.0
Summary: This is submit50, with which you can submit solutions to problems for CS50.
Home-page: https://github.com/cs50/submit50
Author: CS50
Author-email: sysadmins@cs50.harvard.edu
License: GPLv3
Location: /usr/local/lib/python3.9/site-packages
Requires: lib50, requests, termcolor
Required-by: 
```

And my OS is: `macOS Big Sur 11.6`

**Comment by StoneCodeKilla** [comment]
I am stuck on this as well, I am having a hard time figuring out how to submit my scratch project!

**Comment by rongxin-liu** [comment]
Please go to [https://submit.cs50.io/upload/cs50/problems/2021/x/scratch](https://submit.cs50.io/upload/cs50/problems/2021/x/scratch) to submit your scratch project.
