### ISSUE TITLE
Submit50 does not work in spite of 2factor authorisation installed

### ISSUE THREAD

**Issue by Launch2021** [cs50/submit50#271]
Have picked up work on CS50 after a 4 months break. Needed to install 2 factor authorisation which I did. I can log into my GitHub account with it. Still, when I want to execute submit50 cs50/problems/2021/x/homepage, I still get an error message (you might be using your password ...).
What can be the problem? I work on a Mac M1 laptop.
It seems I have submit50 3.1.0 installed.
Thanks.
This is the error message:
You might be using your GitHub password to log in, but that's no longer possible. But you can still use check50 and submit50! See https://cs50.ly/github for instructions.
Make sure your username and/or personal access token are valid and submit50 is enabled for your account. To enable submit50, please go to 
https://submit.cs50.io in your web browser and try again. For instructions on how to set up a personal access token, please visit 
https://cs50.ly/github
Submission cancelled.

**Comment by Launch2021** [comment]
I am working from Germany, btw

**Comment by rongxin-liu** [comment]
Please run this command in your project folder and send the output to `sysadmins@cs50.harvard.edu`:

`submit50 --log-level=debug cs50/problems/2021/x/homepage`

Thank you!
