### ISSUE TITLE
Combined file tree for projects

### ISSUE THREAD

**Issue by yashpalgoyal1304** [cs50/submit50#272]
### Summary
All the project files should be available in a single file tree at least somewhere

#### Current
* So, currently, every problem (pset, or lab) is on its own branch. 
* I am assuming that it's that way for ease in automation.
* And it also can set the problem the student is currently working on as default, which kinda helped me
![image](https://user-images.githubusercontent.com/19423063/144732261-889cd212-deee-47ef-84d0-5a3708b3e88a.png)
* But this debars the user from downloading their submissions as one folder

#### Proposal
The proposal is to
* make one more branch and cherry-picking all the commits to that branch to have a unified file structure
* ~if that's not reserved for any other thing already, then the `main` branch can be used for this purpose too~
* so, example:

```
branch : projects-unified-tree

/                   (branch-root)
└── cs50
    └── problems
        └── 2021
            └── x
                ├── scratch
                ├── hello
                ├── mario
                │   ├── more
                │   ...
                ...
```

------
Footer:

* might be related?: https://github.com/cs50/submit50/issues/19
* The adcii file tree representation took from: F-droid fastlane structure implementation 
https://gitlab.com/-/snippets/1895688

**Comment by dmalan** [comment]
Hm, an interesting idea, thanks. I suspect we wouldn't want to store files redundantly on an additional branch, but we'll give some thought to how to automate checking out all branches somehow!

**Comment by goyalyashpal** [comment]
hi @dmalan !  were you able to find some solution to this?
