### ISSUE TITLE
Hello Good People, i need your help on this problem (mv: cannot stat 'hello.c': No such file or directory) in  CS50x IDE.

### ISSUE THREAD

**Issue by KClayouson** [cs50/submit50#274]
I have tried to solve this problem now two days nothing else i do only this, but unfortunately my knowledge become limted on this. if anybody can help me on how to solve it, i will appreached it

**Comment by dmalan** [comment]
For questions on problem sets, best to post in any of https://cs50.harvard.edu/x/2021/communities/!
