### ISSUE TITLE
Not working Always Offline 

### ISSUE THREAD

**Issue by dayojohn19** [cs50/submit50#296]
Tried to reinstall submit50 but still same issue
submit50 web50/projects/2020/x/capstone
>> Connecting..........
>> Could not connect to GitHub, it seems you are offline.
Submission cancelled.

**Comment by rongxin-liu** [comment]
This suggests that your computer is having issues connecting to git's remote server. It could also be a GitHub problem at that time. Are you still experiencing the same issue?

**Comment by dayojohn19** [comment]
Done now thank you, it seems its a network connection problem thanks 


Sent from Yahoo Mail


On Sunday, September 11, 2022, 15:23, Rongxin Liu ***@***.***> wrote:




This suggests that your computer is having issues connecting to git's remote server. It could also be a GitHub problem at that time. Are you still experiencing the same issue?
