### ISSUE TITLE
Submit50

### ISSUE THREAD

**Issue by Alashhar** [cs50/submit50#303]
Hi....

I have problem to get the process of submission the problems, I tried to follow the steps on this website https://cs50.readthedocs.io/submit50/, which a mystery for me, for first time programming, but it was not successful as you can see what's in terminal wrote:

submit50 usage: submit50 [-h] [--logout] [--log-level {debug,info,warning,error}] [-V] slug submit50: error: the following arguments are required: slug $ submit50 [-h] [--logout] [--log-level {debug,info,warning,error}] [-V] slug usage: submit50 [-h] [--logout] [--log-level {debug,info,warning,error}] [-V] slug submit50: error: unrecognized arguments: [--logout] [--log-level debug] info] warning] error] [-V] slug

Is there a manual way to submit my files? or a video can explain it in detail?
![image](https://user-images.githubusercontent.com/58273740/197534761-34ec9461-d142-415d-8774-a05dcf28ed6c.png)
![image](https://user-images.githubusercontent.com/58273740/197534865-20211469-72c9-4d1e-9623-42a12a7e77d5.png)
![Capture](https://user-images.githubusercontent.com/58273740/197535158-13cd1c95-49c3-441a-9165-17abafbb25cd.JPG)
![Capture2](https://user-images.githubusercontent.com/58273740/197535162-c61f9eaf-c3d0-49d3-8a28-3914b0dad5a0.JPG)

**Comment by rongxin-liu** [comment]
Please make sure your terminal location is in your `indoor` folder, then run `submit50` commands. You can utilize the `cd` command to change directory in your terminal.
