### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by wafaalthaidy** [cs50/submit50#307]
[](https://github.com/wafaalthaidy/final-project-/releases)

**Comment by llenel22** [comment]
Dear Professor David Malan, I received an email with the message "Closed #307 as not planned.".

I signed up for the course through "edx courses",
Can I continue uploading my submissions as I have done so far?
I understand from the message that the only thing I have closed at this moment is the part of the final project, right?
I thank you for this course and I await your instructions.
