### ISSUE TITLE
code.cs50.io issue

### ISSUE THREAD

**Issue by sucukspor** [cs50/submit50#310]
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/122697492/228911450-c792db8d-c7ef-402f-b681-a2c05ed2db5e.png)

hello guys, I could use code.cs50.io until today. However, suddenly it stops workinig I can't use terminal at all it also says "Please update your includepath".Currently I can't load anything at all. Any help would be appreciated.

**Comment by rongxin-liu** [comment]
Please follow this documentation to exit recovery mode:
https://cs50.readthedocs.io/code/#codespaces-run-into-recovery-mode
