### ISSUE TITLE
Need help with submit50 --Invalid Slug

### ISSUE THREAD

**Issue by maryvisa123** [cs50/submit50#313]
I recently set up python locally and can never get submit50 to work.

At first it's always " Could not connect to GitHub, it seems you are offline. Submission cancelled. " and today it switched to "Invalid slugs" as you can see here:

maryvisa123@LAPTOP-FD5C7DPB:/mnt/c/Users/maryv/Desktop/cs50g/flappy$ submit50 games50/projects/2018/x/flappy

Connecting....

Invalid slug: games50/projects/2018/x/flappy

Submission cancelled.

I'm pretty sure I didn't make any typo because I copied and pasted the command from the website. And just for the testing sake, I also tried a few other submit50 commands that worked while I was using Codespace for cs50x, still got the same result.

For the reference this is what I got running the debug command:

maryvisa123@LAPTOP-FD5C7DPB:/mnt/c/Users/maryv/Desktop/cs50g/flappy$ submit50 --log-level debug slug

Invalid slug

Traceback (most recent call last):

File "/home/maryvisa123/.local/bin/submit50", line 8, in <module>

sys.exit(main())

File "/home/maryvisa123/.local/lib/python3.10/site-packages/submit50/__main__.py", line 218, in main

user_name, commit_hash, message = lib50.push("submit50", args.slug, CONFIG_LOADER, prompt=prompt)

File "/home/maryvisa123/.local/lib/python3.10/site-packages/lib50/_api.py", line 84, in push

slug = Slug.normalize_case(slug)

File "/home/maryvisa123/.local/lib/python3.10/site-packages/lib50/_api.py", line 820, in normalize_case

raise InvalidSlugError(_("Invalid slug"))

lib50._errors.InvalidSlugError: Invalid slug

I really don't know what to do now(crying face). Any suggestions or help would be really appreciated!

**Comment by rongxin-liu** [comment]
Could you please try running `submit50 --log-level=debug games50/projects/2018/x/flappy` and send the output to sysadmins@cs50.harvard.edu?

**Comment by maryvisa123** [comment]
> Could you please try running `submit50 --log-level=debug games50/projects/2018/x/flappy` and send the output to [sysadmins@cs50.harvard.edu](mailto:sysadmins@cs50.harvard.edu)?

Sure thing! Will do that right away.
