### ISSUE TITLE
Unable to open Codespace

### ISSUE THREAD

**Issue by chloeee47** [cs50/submit50#332]
When i try to open my codespace i get to the window that says "Setting up your codespace" and a black window below where is says "connecting" but nothing happens.  It never takes me into the code space.  What can i do to fix this issue?

**Comment by rongxin-liu** [comment]
If using Safari, please make sure your browser is up to date, or use Chrome.

Please note that this is not the place to submit codespace or assignment issues. Please email sysadmins@cs50.harvard.edu for such inquiries.

Thanks.
