### ISSUE TITLE
support python 2

### ISSUE THREAD

**Issue by kzidane** [cs50/submit50#37]
Right now, this package requires `getch`, which is for Python 3+, and the `submit50`script uses Python-3-specific features like [`raise ... from`](https://github.com/cs50/submit50/blob/0dcd808ae0b7a694920cd0952e4be6289cd61b49/opt/cs50/submit50/bin/submit50.py#L50). There's [`getch-1.0-python2.tar.gz`](https://pypi.python.org/pypi/getch#downloads), which is `getch` for Python 2. So if we can get this to install on systems running Python 2, and `getch` to install on systems running Python 3+, any idea whether it'd be feasible to get `submit50` to support Python 2 as well, @brianyu28?

cc @dmalan

**Comment by dmalan** [comment]
We should indeed eliminate our `python3` dependencies methinks, else users won't be able to install `submit50` on their own machines as easily (e.g, Macs). @brianyu28 do you want to take a stab at this one?

**Comment by dmalan** [comment]
Thanks to @brianyu28!
