### ISSUE TITLE
 have submit50 autoupdate via pip and also check cs50.me for latest version

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#78]
Now that `submit50` is on PyPi, would this be more elegant? Instead of autoupdate, could just ask user to update? Bad to rely on `pip`?

**Comment by kzidane** [comment]
I thought `submit50`'s version on CS50.me is the _minimum version that's compatible with CS50.me_? I mean, ideally, we'd want the user to always upgrade to the latest version, but might be better to keep the application working until the user has to upgrade, unless we want to avoid the headache of keeping track of the minimum version that's compatible with CS50.me at any given time?

**Comment by dmalan** [comment]
It is. Just thinking it might be good practice for our `*50` apps to inform the user when newer versions are available in general, so that they're always running the latest, even if they've not run `update50` recently. Else folks using, e.g., `submit50` on their own machine might never think to update.

**Comment by kzidane** [comment]
Ah, that's probably a good idea! +1

**Comment by dmalan** [comment]
@brianyu28 want to add your pypi code from `check50` too?

**Comment by brianyu28** [comment]
Likewise closing
