### ISSUE TITLE
change call to bindtextdomain to find `locale` dir based on where package gets installed

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#94]
If `submit50` gets installed by `pip` in, e.g., `/opt/pyenv/shims/submit50`, where will `locale` end up? Can we locate it dynamically so that we can still test during dev by running `python submit50.py`?

https://github.com/cs50/submit50/blob/gettext/submit50.py#L37

**Comment by dmalan** [comment]
@kzidane mind tackling for v2.4.1?

**Comment by dmalan** [comment]
@kzidane++!

**Comment by kzidane** [comment]
Sorry! On it ...

**Comment by kzidane** [comment]
https://github.com/cs50/submit50/issues/135
